#define ERROR_HISTORY_LEN 15
#define TTGO_THRESHOLD 0.1
#define HOVER_THRESHOLD 0.2

#define TERRAIN_SEARCH_RADIUS 400
#define TERRAIN_FOREST 0
#define TERRAIN_OPEN 1
#define TERRAIN_URBAN 2

#define CONTACT_CLOSE 0
#define CONTACT_MEDIUM_THRESHOLD 250
#define CONTACT_MEDIUM 1
#define CONTACT_FAR_THRESHOLD 600
#define CONTACT_FAR 2
#define CONTACT_MAX_DISTANCE 1500

#define FLY_COMBAT_RANGE 65
#define ROOF_COMBAT_RANGE 175